# Generated by Django 5.1.6 on 2025-02-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
    ]
