# Generated by Django 5.1.6 on 2025-02-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='img',
        ),
    ]
